-- MySQL Script generated by MySQL Workbench
-- Tue Feb 20 15:13:50 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `Fair`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Fair` ;

CREATE TABLE IF NOT EXISTS `Fair` (
  `FairID` INT NOT NULL,
  `FairName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`FairID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `School`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `School` ;

CREATE TABLE IF NOT EXISTS `School` (
  `SchoolID` INT NOT NULL AUTO_INCREMENT,
  `SName` VARCHAR(100) NOT NULL,
  `KeyTeacher` VARCHAR(100) NOT NULL,
  `City` VARCHAR(50) NOT NULL,
  `Type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`SchoolID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Category` ;

CREATE TABLE IF NOT EXISTS `Category` (
  `CategoryID` INT NOT NULL,
  `Description` VARCHAR(120) NOT NULL,
  PRIMARY KEY (`CategoryID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Registration`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Registration` ;

CREATE TABLE IF NOT EXISTS `Registration` (
  `RegistrationID` INT NOT NULL AUTO_INCREMENT,
  `LName` VARCHAR(50) NOT NULL,
  `FName` VARCHAR(50) NOT NULL,
  `ProjTitle` VARCHAR(255) NOT NULL,
  `Age` INT NOT NULL,
  `Gener` VARCHAR(10) NOT NULL,
  `City` VARCHAR(45) NOT NULL,
  `State` VARCHAR(2) NOT NULL,
  `Zip` INT(5) NOT NULL,
  `AdultSponsor` VARCHAR(100) NOT NULL,
  `Grade` INT NOT NULL,
  `Class` INT NOT NULL,
  `FkFairID` INT NOT NULL,
  `Score1` INT NULL,
  `Score2` INT NULL,
  `Total` DECIMAL(4,1) NULL,
  `StanDev1` DECIMAL(11,10) NULL,
  `StanDev2` DECIMAL(11,10) NULL,
  `Average` DECIMAL(11,10) NULL,
  `FkSchoolID` INT NOT NULL,
  `FkCategoryID` INT NOT NULL,
  PRIMARY KEY (`RegistrationID`),
  CONSTRAINT `fk_Registration_Fair`
    FOREIGN KEY (`FkFairID`)
    REFERENCES `Fair` (`FairID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Registration_School1`
    FOREIGN KEY (`FkSchoolID`)
    REFERENCES `School` (`SchoolID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Registration_Category1`
    FOREIGN KEY (`FkCategoryID`)
    REFERENCES `Category` (`CategoryID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Judge`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Judge` ;

CREATE TABLE IF NOT EXISTS `Judge` (
  `JudgeID` INT NOT NULL AUTO_INCREMENT,
  `LName` VARCHAR(50) NOT NULL,
  `FName` VARCHAR(50) NOT NULL,
  `Email` VARCHAR(50) NOT NULL,
  `Categories` VARCHAR(45) NOT NULL,
  `JudgeSet` VARCHAR(45) NULL,
  `FkFairID` INT NOT NULL,
  `FkCategoryID` INT NOT NULL,
  PRIMARY KEY (`JudgeID`),
  CONSTRAINT `fk_Judge_Fair1`
    FOREIGN KEY (`FkFairID`)
    REFERENCES `Fair` (`FairID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Judge_Category1`
    FOREIGN KEY (`FkCategoryID`)
    REFERENCES `Category` (`CategoryID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Score`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Score` ;

CREATE TABLE IF NOT EXISTS `Score` (
  `ScoreID` INT NOT NULL AUTO_INCREMENT,
  `Score1` INT NULL,
  `Score2` INT NULL,
  `Total` DECIMAL(2) NULL,
  `StandDev1` DECIMAL(5) NULL,
  `StandDev2` DECIMAL(5) NULL,
  `Average` DECIMAL(7) NULL,
  `Rank` INT NULL,
  PRIMARY KEY (`ScoreID`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
