-- MySQL Script generated by MySQL Workbench
-- Sun Mar  4 14:28:53 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering


-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
USE bhvalent;

DROP TABLE IF EXISTS Fair, School, Category, Class, Registration, Judge, Score, SetJudge, JudgeRegistrant;
-- -----------------------------------------------------
-- Table `Fair`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `Fair` (
  `FairID` INT NOT NULL AUTO_INCREMENT,
  `FairName` VARCHAR(45) NOT NULL,
  `Year` YEAR NOT NULL,
  PRIMARY KEY (`FairID`)
);
-- ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `School`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `School` (
  `SchoolID` INT NOT NULL AUTO_INCREMENT,
  `SName` VARCHAR(100) NOT NULL,
  `KeyTeacher` VARCHAR(100) NOT NULL,
  `City` VARCHAR(50) NOT NULL,
  `Type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`SchoolID`)
);
-- ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Category`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `Category` (
  `CategoryID` INT NOT NULL,
  `Description` VARCHAR(120) NOT NULL,
  PRIMARY KEY (`CategoryID`)
);
-- ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Class`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `Class` (
  `ClassID` INT NOT NULL AUTO_INCREMENT,
  `Class` INT NOT NULL,
  `Grade` INT NOT NULL,
  PRIMARY KEY (`ClassID`)
);
-- ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Registration`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `Registration` (
  `RegistrationID` INT NOT NULL AUTO_INCREMENT,
  `LName` VARCHAR(50) NOT NULL,
  `FName` VARCHAR(50) NOT NULL,
  `ProjTitle` VARCHAR(255) NOT NULL,
  `Age` INT NOT NULL,
  `Gender` VARCHAR(10) NOT NULL,
  `City` VARCHAR(45) NOT NULL,
  `State` VARCHAR(2) NOT NULL,
  `Zip` INT(5) NOT NULL,
  `AdultSponsor` VARCHAR(100) NOT NULL,
  `FKFairID` INT NOT NULL,
  `FKSchoolID` INT NOT NULL,
  `FKCategoryID` INT NOT NULL,
  `FKClassID` INT NOT NULL,
  `Score1` INT NULL,
  `Score2` INT NULL,
  `Total` DECIMAL(4,1) NULL,
  `StanDev1` DECIMAL(10,8) NULL,
  `StanDev2` DECIMAL(10,8) NULL,
  `Average` DECIMAL(11,9) NULL,
  `Rank` INT NULL,
  PRIMARY KEY (`RegistrationID`),
  CONSTRAINT `fk_Registration_Fair`
    FOREIGN KEY (`FKFairID`)
    REFERENCES `Fair` (`FairID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Registration_School1`
    FOREIGN KEY (`FKSchoolID`)
    REFERENCES `School` (`SchoolID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Registration_Category1`
    FOREIGN KEY (`FKCategoryID`)
    REFERENCES `Category` (`CategoryID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Registration_Class1`
    FOREIGN KEY (`FKClassID`)
    REFERENCES `Class` (`ClassID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);
-- ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Judge`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `Judge` (
  `JudgeID` INT NOT NULL AUTO_INCREMENT,
  `LName` VARCHAR(50) NOT NULL,
  `FName` VARCHAR(50) NOT NULL,
  `Email` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`JudgeID`)
);
-- ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SetJudge`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `SetJudge` (
  `SetJudgeID` INT NOT NULL AUTO_INCREMENT,
  `FKFairID` INT NOT NULL,
  `FKJudgeID` INT NOT NULL,
  `FKCategoryID` INT NOT NULL,
  PRIMARY KEY (`SetJudgeID`),
  CONSTRAINT `fk_Fair_Judge_Fair1`
    FOREIGN KEY (`FKFairID`)
    REFERENCES `Fair` (`FairID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fair_Judge_Judge1`
    FOREIGN KEY (`FKJudgeID`)
    REFERENCES `Judge` (`JudgeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fair_Judge_Category1`
    FOREIGN KEY (`FKCategoryID`)
    REFERENCES `Category` (`CategoryID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);
-- ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JudgeRegistrant`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `JudgeRegistrant` (
  `FKSetJudgeID` INT NOT NULL,
  `FKRegistrationID` INT NOT NULL,
  `SetNumber` INT NOT NULL,
  PRIMARY KEY (`FKSetJudgeID`, `FKRegistrationID`),
  CONSTRAINT `fk_JudgeRegistrant_SetJudge1`
    FOREIGN KEY (`FKSetJudgeID`)
    REFERENCES `SetJudge` (`SetJudgeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_JudgeRegistrant_Registration1`
    FOREIGN KEY (`FKRegistrationID`)
    REFERENCES `Registration` (`RegistrationID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);
-- ENGINE = InnoDB;



